baseURL = 'https://docs.eazyautodelete.xyz/'
languageCode = 'en-us'
title = 'Docs | EazyAutodelete'
theme = 'hugo-book'
enableGitInfo = true
cleanDestinationDir = true

[params]
  BookTheme = 'dark'
  BookSection = '*'
  BookComments = false

[minify]
  minifyOutput = true